/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as AppIndexImport } from './routes/app/index'
import { Route as AppWorkspaceWorkspaceIdImport } from './routes/app/workspace/$workspaceId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRoute,
} as any)

const AppWorkspaceWorkspaceIdRoute = AppWorkspaceWorkspaceIdImport.update({
  id: '/app/workspace/$workspaceId',
  path: '/app/workspace/$workspaceId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof rootRoute
    }
    '/app/workspace/$workspaceId': {
      id: '/app/workspace/$workspaceId'
      path: '/app/workspace/$workspaceId'
      fullPath: '/app/workspace/$workspaceId'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app': typeof AppIndexRoute
  '/app/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app': typeof AppIndexRoute
  '/app/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/': typeof AppIndexRoute
  '/app/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signup' | '/app' | '/app/workspace/$workspaceId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/app' | '/app/workspace/$workspaceId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/app/'
    | '/app/workspace/$workspaceId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AppIndexRoute: typeof AppIndexRoute
  AppWorkspaceWorkspaceIdRoute: typeof AppWorkspaceWorkspaceIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AppIndexRoute: AppIndexRoute,
  AppWorkspaceWorkspaceIdRoute: AppWorkspaceWorkspaceIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/signup",
        "/app/",
        "/app/workspace/$workspaceId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/app/": {
      "filePath": "app/index.tsx"
    },
    "/app/workspace/$workspaceId": {
      "filePath": "app/workspace/$workspaceId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
