/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WorkspaceImport } from './routes/workspace'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as WorkspaceIndexImport } from './routes/workspace/index'
import { Route as WorkspaceWorkspaceIdImport } from './routes/workspace/$workspaceId'
import { Route as GoogleCallbackImport } from './routes/google/callback'
import { Route as AuthSignupImport } from './routes/_auth/signup'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as WorkspaceWorkspaceIdIndexImport } from './routes/workspace/$workspaceId/index'
import { Route as WorkspaceWorkspaceIdTasksImport } from './routes/workspace/$workspaceId/tasks'
import { Route as WorkspaceWorkspaceIdSettingsImport } from './routes/workspace/$workspaceId/settings'
import { Route as WorkspaceWorkspaceIdMembersImport } from './routes/workspace/$workspaceId/members'
import { Route as WorkspaceWorkspaceIdProjectIdIndexImport } from './routes/workspace/$workspaceId/$projectId/index'

// Create/Update Routes

const WorkspaceRoute = WorkspaceImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WorkspaceIndexRoute = WorkspaceIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)

const WorkspaceWorkspaceIdRoute = WorkspaceWorkspaceIdImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => WorkspaceRoute,
} as any)

const GoogleCallbackRoute = GoogleCallbackImport.update({
  id: '/google/callback',
  path: '/google/callback',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const WorkspaceWorkspaceIdIndexRoute = WorkspaceWorkspaceIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceWorkspaceIdRoute,
} as any)

const WorkspaceWorkspaceIdTasksRoute = WorkspaceWorkspaceIdTasksImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => WorkspaceWorkspaceIdRoute,
} as any)

const WorkspaceWorkspaceIdSettingsRoute =
  WorkspaceWorkspaceIdSettingsImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)

const WorkspaceWorkspaceIdMembersRoute =
  WorkspaceWorkspaceIdMembersImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)

const WorkspaceWorkspaceIdProjectIdIndexRoute =
  WorkspaceWorkspaceIdProjectIdIndexImport.update({
    id: '/$projectId/',
    path: '/$projectId/',
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof AuthImport
    }
    '/google/callback': {
      id: '/google/callback'
      path: '/google/callback'
      fullPath: '/google/callback'
      preLoaderRoute: typeof GoogleCallbackImport
      parentRoute: typeof rootRoute
    }
    '/workspace/$workspaceId': {
      id: '/workspace/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdImport
      parentRoute: typeof WorkspaceImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexImport
      parentRoute: typeof WorkspaceImport
    }
    '/workspace/$workspaceId/members': {
      id: '/workspace/$workspaceId/members'
      path: '/members'
      fullPath: '/workspace/$workspaceId/members'
      preLoaderRoute: typeof WorkspaceWorkspaceIdMembersImport
      parentRoute: typeof WorkspaceWorkspaceIdImport
    }
    '/workspace/$workspaceId/settings': {
      id: '/workspace/$workspaceId/settings'
      path: '/settings'
      fullPath: '/workspace/$workspaceId/settings'
      preLoaderRoute: typeof WorkspaceWorkspaceIdSettingsImport
      parentRoute: typeof WorkspaceWorkspaceIdImport
    }
    '/workspace/$workspaceId/tasks': {
      id: '/workspace/$workspaceId/tasks'
      path: '/tasks'
      fullPath: '/workspace/$workspaceId/tasks'
      preLoaderRoute: typeof WorkspaceWorkspaceIdTasksImport
      parentRoute: typeof WorkspaceWorkspaceIdImport
    }
    '/workspace/$workspaceId/': {
      id: '/workspace/$workspaceId/'
      path: '/'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof WorkspaceWorkspaceIdIndexImport
      parentRoute: typeof WorkspaceWorkspaceIdImport
    }
    '/workspace/$workspaceId/$projectId/': {
      id: '/workspace/$workspaceId/$projectId/'
      path: '/$projectId'
      fullPath: '/workspace/$workspaceId/$projectId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdProjectIdIndexImport
      parentRoute: typeof WorkspaceWorkspaceIdImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface WorkspaceWorkspaceIdRouteChildren {
  WorkspaceWorkspaceIdMembersRoute: typeof WorkspaceWorkspaceIdMembersRoute
  WorkspaceWorkspaceIdSettingsRoute: typeof WorkspaceWorkspaceIdSettingsRoute
  WorkspaceWorkspaceIdTasksRoute: typeof WorkspaceWorkspaceIdTasksRoute
  WorkspaceWorkspaceIdIndexRoute: typeof WorkspaceWorkspaceIdIndexRoute
  WorkspaceWorkspaceIdProjectIdIndexRoute: typeof WorkspaceWorkspaceIdProjectIdIndexRoute
}

const WorkspaceWorkspaceIdRouteChildren: WorkspaceWorkspaceIdRouteChildren = {
  WorkspaceWorkspaceIdMembersRoute: WorkspaceWorkspaceIdMembersRoute,
  WorkspaceWorkspaceIdSettingsRoute: WorkspaceWorkspaceIdSettingsRoute,
  WorkspaceWorkspaceIdTasksRoute: WorkspaceWorkspaceIdTasksRoute,
  WorkspaceWorkspaceIdIndexRoute: WorkspaceWorkspaceIdIndexRoute,
  WorkspaceWorkspaceIdProjectIdIndexRoute:
    WorkspaceWorkspaceIdProjectIdIndexRoute,
}

const WorkspaceWorkspaceIdRouteWithChildren =
  WorkspaceWorkspaceIdRoute._addFileChildren(WorkspaceWorkspaceIdRouteChildren)

interface WorkspaceRouteChildren {
  WorkspaceWorkspaceIdRoute: typeof WorkspaceWorkspaceIdRouteWithChildren
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceWorkspaceIdRoute: WorkspaceWorkspaceIdRouteWithChildren,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/workspace': typeof WorkspaceRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/google/callback': typeof GoogleCallbackRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRouteWithChildren
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/$workspaceId/members': typeof WorkspaceWorkspaceIdMembersRoute
  '/workspace/$workspaceId/settings': typeof WorkspaceWorkspaceIdSettingsRoute
  '/workspace/$workspaceId/tasks': typeof WorkspaceWorkspaceIdTasksRoute
  '/workspace/$workspaceId/': typeof WorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/$projectId': typeof WorkspaceWorkspaceIdProjectIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/google/callback': typeof GoogleCallbackRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/workspace/$workspaceId/members': typeof WorkspaceWorkspaceIdMembersRoute
  '/workspace/$workspaceId/settings': typeof WorkspaceWorkspaceIdSettingsRoute
  '/workspace/$workspaceId/tasks': typeof WorkspaceWorkspaceIdTasksRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/$projectId': typeof WorkspaceWorkspaceIdProjectIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/workspace': typeof WorkspaceRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/google/callback': typeof GoogleCallbackRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRouteWithChildren
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/$workspaceId/members': typeof WorkspaceWorkspaceIdMembersRoute
  '/workspace/$workspaceId/settings': typeof WorkspaceWorkspaceIdSettingsRoute
  '/workspace/$workspaceId/tasks': typeof WorkspaceWorkspaceIdTasksRoute
  '/workspace/$workspaceId/': typeof WorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/$projectId/': typeof WorkspaceWorkspaceIdProjectIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/workspace'
    | '/login'
    | '/signup'
    | '/google/callback'
    | '/workspace/$workspaceId'
    | '/workspace/'
    | '/workspace/$workspaceId/members'
    | '/workspace/$workspaceId/settings'
    | '/workspace/$workspaceId/tasks'
    | '/workspace/$workspaceId/'
    | '/workspace/$workspaceId/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/signup'
    | '/google/callback'
    | '/workspace'
    | '/workspace/$workspaceId/members'
    | '/workspace/$workspaceId/settings'
    | '/workspace/$workspaceId/tasks'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/workspace'
    | '/_auth/login'
    | '/_auth/signup'
    | '/google/callback'
    | '/workspace/$workspaceId'
    | '/workspace/'
    | '/workspace/$workspaceId/members'
    | '/workspace/$workspaceId/settings'
    | '/workspace/$workspaceId/tasks'
    | '/workspace/$workspaceId/'
    | '/workspace/$workspaceId/$projectId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  GoogleCallbackRoute: typeof GoogleCallbackRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  GoogleCallbackRoute: GoogleCallbackRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/workspace",
        "/google/callback"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/login",
        "/_auth/signup"
      ]
    },
    "/workspace": {
      "filePath": "workspace.tsx",
      "children": [
        "/workspace/$workspaceId",
        "/workspace/"
      ]
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx",
      "parent": "/_auth"
    },
    "/_auth/signup": {
      "filePath": "_auth/signup.tsx",
      "parent": "/_auth"
    },
    "/google/callback": {
      "filePath": "google/callback.tsx"
    },
    "/workspace/$workspaceId": {
      "filePath": "workspace/$workspaceId.tsx",
      "parent": "/workspace",
      "children": [
        "/workspace/$workspaceId/members",
        "/workspace/$workspaceId/settings",
        "/workspace/$workspaceId/tasks",
        "/workspace/$workspaceId/",
        "/workspace/$workspaceId/$projectId/"
      ]
    },
    "/workspace/": {
      "filePath": "workspace/index.tsx",
      "parent": "/workspace"
    },
    "/workspace/$workspaceId/members": {
      "filePath": "workspace/$workspaceId/members.tsx",
      "parent": "/workspace/$workspaceId"
    },
    "/workspace/$workspaceId/settings": {
      "filePath": "workspace/$workspaceId/settings.tsx",
      "parent": "/workspace/$workspaceId"
    },
    "/workspace/$workspaceId/tasks": {
      "filePath": "workspace/$workspaceId/tasks.tsx",
      "parent": "/workspace/$workspaceId"
    },
    "/workspace/$workspaceId/": {
      "filePath": "workspace/$workspaceId/index.tsx",
      "parent": "/workspace/$workspaceId"
    },
    "/workspace/$workspaceId/$projectId/": {
      "filePath": "workspace/$workspaceId/$projectId/index.tsx",
      "parent": "/workspace/$workspaceId"
    }
  }
}
ROUTE_MANIFEST_END */
